name: Vagrant Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'
  push:
    branches: [main, develop, vagrant/*]
  pull_request:
    branches: [main, develop]

jobs:
  vagrant-test:
    runs-on: macos-12
    # runs-on: macos-latest
    # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
    # @see https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    strategy:
      matrix:
        runtime:
          - freebsd
    name: Vagrant ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ${{ matrix.runtime }}
        run: bash ./test/runtime --driver vagrant --build --run ${{ matrix.runtime }}
